import 'dart:io';

import 'package:dio/dio.dart';
import 'package:news_app_clean_architecture/core/constants/constants.dart';
import 'package:news_app_clean_architecture/core/resources/remote_exception.dart';

import '../../../domain/entities/news_category.dart';
import '../../models/article.dart';
import 'news_api_service.dart';

/// The only class in the app that talks to the News API.
///
/// [NewsApiService] is generated by Retrofit and answers in the HTTP client's
/// own vocabulary — an `HttpResponse`, a `DioException`, a status code. This
/// class is the boundary where that vocabulary ends: headlines leave as
/// models and anything else leaves as a [RemoteException], so the repository
/// above never imports Dio (rule 1.2.4).
class NewsRemoteDataSource {
  final NewsApiService _apiService;

  const NewsRemoteDataSource(this._apiService);

  /// Headlines for [category].
  ///
  /// Anything but a 200 is thrown rather than returned: an empty list would
  /// tell the reader there is no news, when in fact nobody asked properly.
  Future<List<ArticleModel>> getNewsArticles(NewsCategory category) async {
    try {
      final httpResponse = await _apiService.getNewsArticles(
        apiKey: newsAPIKey,
        country: countryQuery,
        category: category.query,
      );

      final statusCode = httpResponse.response.statusCode;

      if (statusCode != HttpStatus.ok) {
        throw RemoteException(
          '$statusCode',
          message: httpResponse.response.statusMessage,
        );
      }

      return httpResponse.data;
    } on DioException catch (error) {
      throw RemoteException(
        error.type.name,
        message: error.message,
        cause: error,
      );
    }
  }
}
